package GUI;

import GUI.ThongKeHeThong.ThongKeDoanhThu;
import GUI.ThongKeHeThong.ThongKeKhachHang;
import GUI.ThongKeHeThong.ThongKeNhaCungCap;
import GUI.ThongKeHeThong.ThongKeSanPhamBanChay;
import GUI.ThongKeHeThong.ThongKeTonKho;
import GUI.ThongKeHeThong.ThongKeTongQuan;
import java.awt.Color;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
/**
 *
 * @author ADMIN
 */
public class ThongKe extends javax.swing.JPanel {

    /**
     * Creates new form ThongKe
     */
    ThongKeTongQuan thongKeTongQuan = new ThongKeTongQuan();
    ThongKeDoanhThu thongKeDoanhThu = new ThongKeDoanhThu();
    ThongKeTonKho thongKeTonKho = new ThongKeTonKho();
    ThongKeKhachHang thongKeKhachHang = new ThongKeKhachHang();
    ThongKeNhaCungCap thongKeNhaCungCap = new ThongKeNhaCungCap();
    ThongKeSanPhamBanChay thongKeSanPhamBanChay = new ThongKeSanPhamBanChay();
    Color BackgroundColor = new Color(240, 247, 250);

    public ThongKe() {
        initComponents();
        thongKe.setOpaque(false);
        this.setBackground(BackgroundColor);
        thongKe.addTab("Tổng quan", thongKeTongQuan);
        thongKe.addTab("Doanh thu", thongKeDoanhThu);
        thongKe.addTab("Kho", thongKeTonKho);
        thongKe.addTab("Khách hàng", thongKeKhachHang);
        thongKe.addTab("Nhà cung cấp", thongKeNhaCungCap);
        thongKe.addTab("Sản phẩm bán chạy", thongKeSanPhamBanChay);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        thongKe = new javax.swing.JTabbedPane();

        setLayout(new java.awt.BorderLayout());
        add(thongKe, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane thongKe;
    // End of variables declaration//GEN-END:variables
}
