/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.PXuat;

import BUS.KhachHangBUS;
import DTO.KhachHangDTO;
import DAO.KhachHangDAO;
import GUI.Panel.TaoPhieuNhap;
import GUI.Panel.TaoPhieuXuatt;
import java.awt.Window;
import java.util.ArrayList;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author this pc
 */
public class ChonKhachHang extends javax.swing.JPanel {
    DefaultTableModel model;
    ArrayList<KhachHangDTO> listKhachHang;
    KhachHangBUS khachHangBUS;
    TaoPhieuNhap taoPhieuNhap;
    private TaoPhieuXuatt taoPhieuXuat;
    /**
     * Creates new form ChonKhachHang
     */
    public ChonKhachHang() {
        initComponents();   
        khachHangBUS = new KhachHangBUS();
        taoPhieuNhap = new TaoPhieuNhap();
        taoPhieuXuat = new TaoPhieuXuatt();
        this.taoPhieuXuat = taoPhieuXuat;
       // taoPhieuXuat = new TaoPhieuXuatt();
        listKhachHang = khachHangBUS.getAllKhachHang();
        
        tblkhachhang.setDefaultEditor(Object.class, null);
        tblkhachhang.setFocusable(false);
        
        LoadDataTable(listKhachHang);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlTop = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        btnchonkhachhang = new javax.swing.JButton();
        pnlBottom = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblkhachhang = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Tìm kiếm");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        btnchonkhachhang.setText("Chọn khách hàng");
        btnchonkhachhang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchonkhachhangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTopLayout = new javax.swing.GroupLayout(pnlTop);
        pnlTop.setLayout(pnlTopLayout);
        pnlTopLayout.setHorizontalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnchonkhachhang, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))
        );
        pnlTopLayout.setVerticalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnchonkhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel1.add(pnlTop, java.awt.BorderLayout.NORTH);

        tblkhachhang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã KH", "Họ tên", "Địa chỉ", "Số điện thoại", "Ngày tham gia"
            }
        ));
        jScrollPane1.setViewportView(tblkhachhang);

        javax.swing.GroupLayout pnlBottomLayout = new javax.swing.GroupLayout(pnlBottom);
        pnlBottom.setLayout(pnlBottomLayout);
        pnlBottomLayout.setHorizontalGroup(
            pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 901, Short.MAX_VALUE)
        );
        pnlBottomLayout.setVerticalGroup(
            pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
        );

        jPanel1.add(pnlBottom, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void btnchonkhachhangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchonkhachhangActionPerformed
        themKhachHang();
    }//GEN-LAST:event_btnchonkhachhangActionPerformed
    
    public int themKhachHang(){
        KhachHangDTO selectedKhachHang = SelectKhachHang();
        int maKh = -1;
        if (selectedKhachHang == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn khách hàng!", "Chưa chọn khách hàng", JOptionPane.WARNING_MESSAGE);
        } else {            
            // Đóng dialog chứa panel
            maKh = selectedKhachHang.getMaKH();
            Window window = SwingUtilities.getWindowAncestor(this); // Lấy ra cửa sổ chứa panel
            if (window instanceof JDialog) {
                JDialog dialog = (JDialog) window;
                dialog.dispose(); // Đóng dialog
            }
        }
        return maKh;
    }
    
//HÀM LẤY RA KHÁCH HÀNG KHI CLICK VÀO KHÁCH HÀNG TRONG BẢNG 
    public KhachHangDTO SelectKhachHang(){
        int SelectedRow = tblkhachhang.getSelectedRow();
        KhachHangDTO result = null;
        if(SelectedRow != -1){
            int makhColumnIndex = taoPhieuNhap.getColumnIndexByName("Mã KH", tblkhachhang);
            int makh = (int) tblkhachhang.getValueAt(SelectedRow, makhColumnIndex);
            result = khachHangBUS.selectByID(makh);
        }
        return result;
    }
    //HÀM HIỆN KHÁCH HÀNG LÊN BẢNG
    public void LoadDataTable(ArrayList<KhachHangDTO> ListKhachHang){
        DefaultTableModel model = (DefaultTableModel) tblkhachhang.getModel();
        model.setRowCount(0);
        for(KhachHangDTO kh : ListKhachHang){
            Object[] rowData = {
                kh.getMaKH(),
                kh.getHoten(),
                kh.getDiachi(),
                kh.getSdt(),
                kh.getNgaythamgia()
            };
            model.addRow(rowData);
        }
        // Tạo renderer để hiển thị nội dung ở giữa ô
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        for (int i = 0; i < tblkhachhang.getColumnCount(); i++) {
            tblkhachhang.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnchonkhachhang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel pnlBottom;
    private javax.swing.JPanel pnlTop;
    private javax.swing.JTable tblkhachhang;
    // End of variables declaration//GEN-END:variables
}
